### ISSUE TITLE
Include 'Models'

### ISSUE THREAD

**Issue by normenmueller** [twskj/pretty-swag#47]
It would be advantageous if the `Models` section could also be included, via a switch, for example.

Within a respective `YAML` file, this is the `definitions` section.

**Comment by twskj** [comment]
Could you elaborate why does the information shown in the schema column is not sufficient?

**Comment by normenmueller** [comment]
To obtain a general overview of the definitions, that is, the data model.

For this, one would like --- so I think --- not to look at the individual paths, but only at the definitions independently.

**Comment by twskj** [comment]
I'll do some experiment and will get back to you. Thanks for your suggestion

**Comment by normenmueller** [comment]
@twskj Awesome! Thx!

**Comment by adoerler** [comment]
Hi,

thanks for creating pretty-swag 👍 

I'm also missing the models section for the following reason:

In my case I've some enums defined in the properties like
```YAML
efinitions:
  TestEntry:
    type: "object"
    required:
    - "testattribute"
      testattribute:
        type: "string"
        description: "Kind of testattribute used."
        enum:
          -  "abc"
          -  "def"
          -  "ghi"
          -  "jkl"
          -  "mno"
```

Although the data is included in the schema column, the possible Enum values are missing. Default values, example and format is missing too.

Please have a look at the swagger Petstore example used by http://editor.swagger.io/
It uses the following YAML:
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml

On http://editor.swagger.io/ it shows
![image](https://user-images.githubusercontent.com/376589/38234838-56565fd6-371f-11e8-8caa-44d4a4cae9d2.png)

After pretty-swag this information about the possible ENUMs, formats, examples and default values are missing:
![image](https://user-images.githubusercontent.com/376589/38234869-76bfdaea-371f-11e8-9ac5-a73156a3505d.png)

Best regards
Andreas
